name: Build and push the latest image if needed

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    branches:
      - main
      - release-*

jobs:
  build:
    if: ${{ github.event_name == 'push' }}
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Build ipfix-collector Docker image
        run: make docker-collector
      - name: Push ipfix-collector Docker image to Antrea Docker registry
        if: ${{ github.repository == 'vmware/go-ipfix' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push antrea/ipfix-collector:latest
  upload-kafka-images:
    if: ${{ github.event_name == 'push' }}
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: Pull, tag and push confluentinc/cp-zookeeper and confluentinc/cp-kafka Docker images to Antrea Docker registry
        if: ${{ github.repository == 'vmware/go-ipfix' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull confluentinc/cp-zookeeper:latest
          docker tag confluentinc/cp-zookeeper:latest antrea/kafka-zookeeper:latest
          docker push antrea/kafka-zookeeper:latest
          docker pull confluentinc/cp-kafka:latest
          docker tag confluentinc/cp-kafka:latest antrea/kafka-broker:latest
          docker push antrea/kafka-broker:latest
